"""Add adherence_metrics table

Revision ID: 5d8632b61aaf
Revises: 
Create Date: 2026-07-30 17:46:19.689703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8632b61aaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adherence_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=True),
    sa.Column('taken', sa.Integer(), nullable=True),
    sa.Column('missed', sa.Integer(), nullable=True),
    sa.Column('late', sa.Integer(), nullable=True),
    sa.Column('adherence_pct', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_adherence_metrics_id'), 'adherence_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adherence_metrics_id'), table_name='adherence_metrics')
    op.drop_table('adherence_metrics')
    # ### end Alembic commands ###
