"""Add Gemini validation fields to medicines

Revision ID: 5f4c83191ae9
Revises: 5d8632b61aaf
Create Date: 2026-07-30 17:50:16.765297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4c83191ae9'
down_revision: Union[str, Sequence[str], None] = '5d8632b61aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('generic_name', sa.String(length=150), nullable=True))
    op.add_column('medicines', sa.Column('validation_source', sa.String(length=50), nullable=True))
    op.add_column('medicines', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'confidence')
    op.drop_column('medicines', 'validation_source')
    op.drop_column('medicines', 'generic_name')
    # ### end Alembic commands ###
